# 다양한 표현 방법들

In [14]:
from konlpy.tag import Komoran
from collections import Counter, defaultdict

import numpy as np
import pandas as pd

In [10]:
news = [
    {
        "title" : "커피 효과, 카페인 때문만 아니었다…디카페인 마셔도 나타난 변화",
        "text" : """
                    커피가 장내 미생물과 기분, 인지 기능에 미치는 영향이 카페인 때문만은 아닐 수 있다는 연구 결과가 나왔다. 카페인이 든 커피뿐 아니라 디카페인 커피를 마신 사람에게서도 장내 미생물과 일부 심리·인지 지표에 변화가 나타났다.

                    최근 과학 전문매체들은 커피 섭취가 장내 미생물과 뇌 기능 사이의 관계에 미치는 영향을 분석한 연구를 소개했다. 연구는 아일랜드 코크대(UCC) 산하 APC 마이크로바이옴 아일랜드 연구진 등이 진행했으며 국제학술지 '네이처 커뮤니케이션즈'에 게재됐다.

                    연구진은 커피가 장내 미생물과 뇌 사이의 양방향 소통 체계인 '마이크로바이오타-장-뇌 축'에 어떤 영향을 미치는지 알아보기 위해 30~50세 건강한 성인 62명을 조사했다.

                    이 가운데 31명은 평소 커피를 마시지 않았고 나머지 31명은 하루 3~5잔을 마시는 사람들이었다. 연구진은 이들의 장내 미생물과 대사산물, 인지 기능, 기분과 스트레스 등을 비교했다.

                    분석 결과 평소 커피를 마시는 사람과 마시지 않는 사람 사이에서는 장내 미생물 구성에 차이가 나타났다. 커피 섭취자에게서는 크립토박테리움(Cryptobacterium)과 에거텔라(Eggerthella) 등 일부 미생물의 상대적 비율이 높았다.

                    장내 미생물이 만들어내는 일부 대사산물에서도 차이가 나타났다. 커피 섭취자는 인돌-3-프로피온산과 인돌-3-카르복스알데히드, 신경전달물질인 감마아미노부티르산(GABA) 수치가 상대적으로 낮았다.

                    연구진은 여기서 한 단계 더 나아가 커피를 끊었다가 다시 마시게 하는 실험을 진행했다.

                    평소 하루 3~5잔의 커피를 마시던 참가자 31명에게 2주 동안 커피와 카페인을 섭취하지 않도록 했다. 이후 이들을 무작위로 나눠 16명에게는 카페인이 든 커피를, 15명에게는 디카페인 커피를 3주 동안 하루 네 차례 마시게 했다.

                    그 결과 커피를 다시 마시기 시작한 뒤 장내 미생물 구성에 변화가 나타났다. 특히 일부 변화는 카페인 커피를 마신 집단과 디카페인 커피를 마신 집단에서 모두 관찰됐다.

                    연구진은 이를 근거로 커피가 장내 환경에 미치는 영향을 카페인만으로 설명하기는 어렵다고 봤다. 커피에는 카페인 외에도 폴리페놀을 비롯해 장내 미생물과 상호작용할 수 있는 다양한 생리활성 성분이 들어 있기 때문이다.

                    기분과 인지 기능을 측정한 결과에서도 카페인 여부에 따라 서로 다른 변화가 관찰됐다.

                    커피를 다시 마신 뒤 카페인 커피와 디카페인 커피를 마신 참가자 모두에서 주관적으로 느끼는 스트레스와 우울 증상, 충동성 지표가 감소했다.

                    카페인 커피를 마신 집단에서는 불안과 심리적 스트레스가 감소했다. 반면 디카페인 커피를 마신 집단에서는 일부 기억 검사 결과와 수면 관련 지표가 개선됐다.

                    이는 커피를 마신 뒤 나타나는 변화가 반드시 카페인 섭취에서만 비롯되는 것은 아닐 가능성을 보여준다. 연구진은 카페인 이외의 커피 성분이 장내 미생물을 변화시키고, 이 같은 변화가 장과 뇌 사이의 상호작용에 관여할 가능성에 주목했다.

                    다만 이번 연구만으로 디카페인 커피가 기억력을 높이거나 우울·스트레스를 줄인다고 단정할 수는 없다. 커피를 끊었다가 다시 마시는 실험에 참여한 사람이 31명에 불과하고, 장내 미생물 변화와 심리·인지 기능 변화 사이의 직접적인 인과관계도 확인되지 않았다.

                    연구진은 향후 더 많은 사람을 대상으로 장기간 연구를 진행해 커피 속 어떤 성분이 장내 미생물에 영향을 주고, 이러한 변화가 뇌와 행동에 어떤 영향을 미치는지 확인할 필요가 있다고 설명했다.
                """
    },
    {
        "title" : "악어 잡아먹는 뱀 사냥 대회…1등은 60마리 잡아",
        "text" : """
                    미국 플로리다주에서 뱀 사냥 대회가 열린다. 대상은 버마왕뱀(버마비단뱀)이다. 원산지는 동남아시아지만 애완동물 거래를 통해 플로리다에 들어왔고 일부가 야생으로 퍼졌다. 암컷 한 마리는 한 번에 50~100개의 알을 낳는다. 천적이 거의 없고 번식력이 매우 높아 개체 수가 급증했다. 버마왕뱀은 토끼나 새는 물론, 사슴이나 악어까지 잡아먹는 최상위 포식자다.

                    일부 포유류 개체수가 90% 이상 감소한 지역이 보고될 정도로 토착 생태계가 크게 교란됐다. 잡힌 버마왕뱀은 평균 길이 180~ 270cm, 가장 큰 것은 580cm다. 전문가들은 완전한 박멸은 사실상 불가하지만, 지속적인 포획이 피해를 줄이는 데 중요하다고 본다.

                    이에 주정부는 '파이톤(비단뱀) 챌린지Python Challenge'를 7월 열흘간 개최했다. 참가자는 온라인 교육을 받고 시험을 치러야 한다. 참가비는 25달러이다. 총상금은 2만5,000달러(3,500만 원), 가장 많은 뱀을 잡은 사람에게는 1만 달러(1,400만 원)가 지급된다. 총기 사용은 금지되며, 동물복지 기준에 맞는 인도적인 포획·안락사가 의무다. 현지 기사는 "이 대회가 단순한 이색 이벤트가 아니라, '시민 참여를 통한 생태계 보전, 외래종 문제에 대한 대중 인식 제고, 실제 개체수 관리'라는 세 가지 목적을 동시에 갖고 있다"며 "다만 버마왕뱀이 수만 마리 이상이어서, 이 대회만으로 문제를 해결할 수는 없다"고 지적했다.
                """
    },
    {
        "title" : "[속보]배드민턴 이소희·백하나, 24년 만에 여자 복식 금빛 스매시",
        "text" : """
                    한국 배드민턴 여자 복식의 간판 이소희-백하나 조가 2026 아이치·나고야 아시안게임에서 금메달을 목에 걸었습니다.

                    세계랭킹 2위인 이소희-백하나 조는 29일 일본 아이치현 이치노미야 시립체육관에서 열린 대회 배드민턴 여자 복식 결승전에서 세계랭킹 1위인 중국의 류성수-탄닝 조를 상대로 2-1(26-28 21-18 21-18) 역전승을 거뒀습니다.

                    한국 배드민턴이 아시안게임 여자 복식에서 정상에 오른 것은 2002년 부산 대회 라경민-이경원 조 이후 24년 만입니다.
                """
    },
    {
        "title" : "“한강=치킨” 공식 깨졌다…요즘 대세는 ‘회’",
        "text" : """
                    치킨·라면으로 대표되던 한강 피크닉의 먹거리 공식이 달라지고 있습니다.

                    요즘 2030 세대 사이에서는 회를 포장해 한강에서 즐기는 이른바 '회크닉(회+피크닉)'이 새로운 트렌드로 떠오르고 있는데요.

                    SNS에는 탁 트인 한강을 배경으로 돗자리를 펴고 회 한 접시를 즐기는 '회크닉 인증샷'이 잇따라 올라오고 있습니다.

                    [김나영 / 가수]
                    "한강에서 회 먹는다는 상상도 해본 적이 없는데, 나는?" "근데 요즘 많이 한대요."

                    회크닉의 대표 코스는 노량진 수산시장에서 회를 포장한 뒤 가까운 한강공원으로 이동하는 건데요.

                    SNS에는 회 포장 맛집부터 이동 경로, 돗자리 펴기 좋은 자리까지 회크닉 코스 정보가 세세하게 공유되고 있습니다.

                    누리꾼들 사이에서는 "신선한 한강 바람 맞으며 먹는 회는 그 자체로 힐링이다", "날씨 추워지기 전에 바짝 즐겨야 한다"는 반응이 나오고 있는데요.

                    선선한 날씨에만 누릴 수 있는 가을 한정 피크닉이라는 점이 회크닉의 매력을 더하고 있는 겁니다.

                    다만 즐기는 사람이 늘어난 만큼 먹고 남은 음식물과 포장 쓰레기에 대한 우려도 나오는데요.

                    먹은 자리는 깨끗하게 치우는 기본적인 피크닉 매너도 함께 챙겨야겠습니다.
                """
    },
    {
        "title" : "LG전자, AI·로봇 사업 호조… 3분기 영업이익 37% 증가",
        "text" : """
                    LG전자가 인공지능(AI) 데이터센터용 냉각 솔루션 수주 확대, 로봇 사업 가시화, 전장 사업 호조 등에 힘입어 실적 개선을 이룰 것이라는 증권가 전망이 나왔다. 대신증권 박강호 연구원은 9월 29일 보고서에서 “신성장 B2B(기업 간 거래) 분야 사업으로 LG전자에 대한 시각이 긍정적으로 변하고 있다”며 투자의견 ‘매수’를 유지하고, 목표주가를 기존24만 원에서27만 원으로 상향했다. LG전자의 전 거래일 종가는 21만4500원이다.

                    박 연구원에 따르면LG전자는 올해 상반기 데이터센터 냉각솔루션 관련 6000억 원의 수주를 확보했다. 3분기와 4분기에도 약 2조~3조 원의 수주가 진행 중인 것으로 추정된다. 박 연구원은 “공급 및 생산 기간을 감안하면 내년 2분기 이후 공조 사업영업이익률이 개선될 것으로 판단된다”고 밝혔다.

                    또한 대신증권은 LG전자의 로봇 사업 확대에 주목했다.“엔비디아와 협력이 구체화됐고, 액츄에이터(구동장치) 내재화와 외부 매출이 시작된 것으로 추정된다”는 것이다.박 연구원은 “LG전자가 로봇과 관련해 양질의 데이터를 확보하고 있는 만큼 소프트웨어 및 핵심부품 내재화를 바탕으로 B2C(기업과 소비자 간 거래)에서 B2B로 로봇 사업 영역을 확대할 것”이라고 전망했다.

                    차량용 전자장비를 만드는 전장사업에서는고부가 매출 비중증가가 긍정적으로 평가됐다. 박 연구원은 헤드램프와 전기차 부품 분야에서 수익성이 추가로 개선돼 올해전장사업 영업이익이전년대비 56.6% 증가한 8910억 원에 이를것으로 봤다.

                    대신증권에 따르면 LG전자의3분기 영업이익은 전년 동기 대비 36.7% 증가한 9419억 원, 매출액은 13.2% 증가한 24조7550억 원으로 추정된다.
                """
    },
    {
        "title" : "“더 높은 금리 찾아줘” AI 은행 예금 빼갈까",
        "text" : """
                    인공지능(이하 AI) 에이전트가 소비자를 대신해 더 높은 금리의 계좌로 예금을 자동 이동시키면 은해의 수익 구조가 흔들릴 수 있다는 경고가 나왔다.

                    28일(현지시간) 블룸버그통신에 따르면 토르스텐 슬록 아폴로글로벌매니지먼트 수석이코노미스트는 ‘에이전트 뱅크런이 오는가(Is an Agentic Bank Run Coming?)’라는 제목의 분석 자료에서 AI 에이전트가 금융시스템에 새로운 위험이 될 수 있다고 지적했다.

                    미국 당좌예금의 전국 평균 금리는 약 0.1%지만 일부 핀테크와 온라인 금융상품은 연 3.3~5%의 금리를 제공한다.

                    지금까지는 계좌를 직접 비교하고 옮기는 번거로움때문에 고객이 기존 은행에 돈을 그대로 두는 경우가 많았다.

                    AI 에이전트가 확산 되면 상황이 달라질 수 있다. AI가 남은 자금을 찾아 금리를 비교한 뒤 실제 계좌 이동까지 대신할 수 있기 때문이다.

                    은행은 낮은 금이로 조달한 예금을 대출에 활용하고 예금금리와 대출금리의 차이에서 수익을 낸다.

                    AI가 고금리 계좌로 예금을 대거 이동시키면 은행들은 고객을 붙잡기 위해 예금금리를 높여야할 가능성이 있다.

                    다만 ‘에이전트 뱅크런’은 아직 현실화한 현상은 아니다. AI 에이전트가 금융업무를 본격적으로 대신하게 될 경우를 가정한 경고에 가깝다.

                    현재 일부 AI 서비스도 계좌 잔액과 거래 내역 등을 확인 할 수 있지만 직접 돈을 이체하는 기능은 제공하지 않는다.

                    시장에서는 관련 우려가 제기됐지만 최근 은행주 하락을 AI 에이전트 우려만으로 설명하기는 어렵다는 분석도 나왔다.
                """
    },
    {
        "title" : """교황도 'AI 위협론' 힘 실었다…"역겨운 음모"라는 트럼프 주장에 정면 반박""",
        "text" : """
                    레오 14세 교황이 AI의 위험을 경고하는 목소리를 가짜뉴스로 치부해서는 안 된다고 못 박았다. AI 인류위협론을 '사기'라고 일축해온 트럼프 미국 대통령과 정반대 입장이다. 교황은 정치권과 AI 업계, 시민사회가 함께 상황을 점검해야 한다고 촉구했다.

                    AP통신에 따르면, 교황은 28일(현지시간) 프랑스 순방을 마치고 돌아오는 전용기에서 기자회견을 하며 이같이 밝혔다. 이 자리에서는 AI의 파멸적 위협을 막으려면 특히 미국과 중국이 무엇을 해야 하느냐는 질문이 나왔고, 교황은 모른 척 물러서 있을 수 없는 문제라며 머리를 맞대고 진지하게 논의해야 한다고 답했다.

                    위협론이 이익을 노린 주장이라는 시각에는 선을 그었다. 교황은 재정적 이익이든 다른 목적이든 그런 의도로 만들어진 가짜뉴스라고 보지 않는다고 말했다. 많은 AI 전문가와 지식인이 내놓은 우려를 진지하게 받아들여야 한다는 것이다.

                    트럼프 대통령과는 반대 입장이다. AI가 인류 종말로 이어질 수 있다는 우려를 사기로 몰아붙였고, 최근 트루스소셜에는 AI와 데이터센터를 겨냥한 '역겨운 음모'가 있으며 이를 반길 나라는 중국뿐이라는 글을 게시한 바 있다. AI 개발 속도를 늦추지 않고 중국과의 경쟁에서 이기겠다는 의지도 거듭 밝혔다.

                    교황은 지속적인 점검을 촉구했다. 정치 지도자와 AI 기업 리더, 사회단체가 함께 모여 이미 벌어진 일과 앞으로 벌어질 수 있는 일을 계속 살펴야 한다고 주문했다. 문제가 없을 것이라며 눈을 감는 것은 책임 있는 태도가 아니라고 지적했다.

                    교황과 트럼프 대통령의 충돌은 이번이 처음이 아니다. 교황은 지난 5월 AI가 인간을 지배하지 못하도록 무장을 해제해야 한다는 내용의 회칙을 발표했고, 이후 AI 논의에 참여하려는 사람들의 의견을 받아왔다. 트럼프 행정부의 이민자 단속과 미국·이스라엘의 대이란 전쟁에도 반대 목소리를 내며 트럼프 대통령과 설전을 벌여왔다.
                """
    },
    {
        "title" : "대형사 스타링크 무료 와이파이 경쟁, LCC는 속앓이",
        "text" : """
                    대한항공과 아시아나항공이 스타링크 기반 무료 기내 와이파이 서비스를 제공하면서 저비용항공사(LCC)의 고민도 깊어지고 있다. LCC는 단거리 노선 비중이 높아 소비자가 비행 중 와이파이를 이용할 수 있는 시간이 상대적으로 짧다. 스타링크 도입에 필요한 설치·운영 비용에 비해 고객 유인 효과가 떨어져 비용 부담만 커질 수 있다는 우려가 제기된다.

                    대한항공과 아시아나항공은 지난 15일부터 스타링크 기반 무료 기내 와이파이 서비스를 시작했다. 미주·유럽·동남아 중장거리 노선 위주로 투입되는 항공기 가운데 대한항공은 에어버스 A350-900 3대와 보잉 B777-300ER 1대 등 총 4대, 아시아나항공은 A350-900 9대와 A330-300 1대 등 총 10대에서 해당 서비스를 제공하고 있다. 대한항공 해당 기체는 일부 단거리 노선에도 투입된다. 승객은 광고를 시청한 뒤 무료로 접속할 수 있다.

                    저궤도 위성 1만여개를 활용하는 스타링크의 데이터 전송 속도는 최대 500Mbps에 달한다. 지상과 유사한 인터넷 환경을 구현해 기내에서도 OTT(온라인동영상서비스) 스트리밍과 웹 검색 등을 원활하게 이용할 수 있다. 서비스 시작 이후 SNS와 유튜브 등에서도 빠른 속도와 편의성에 대한 긍정적인 반응이 이어졌다.

                    대한항공은 통합 이후인 2027년 말까지 운항 중인 대부분의 항공기에서 무료 와이파이 서비스를 제공할 계획이다. 한진그룹 소속 LCC로도 서비스를 확대한다. 진에어는 보잉 737-8 기종부터 스타링크 시스템을 적용하고 에어부산과 에어서울은 현재 도입 기종을 검토 중이다.

                    LCC에서는 스타링크 효과가 미미할 수 있다는 목소리도 나온다. 승객이 실제 와이파이를 이용하는 시간은 짧은 반면 설치와 운영에는 상당한 비용이 들기 때문이다.

                    블룸버그에 따르면 스타링크 초기 장비 비용은 항공기 대당 30만~50만달러(약 4억~7억원)이며 좌석당 월 이용료가 별도로 붙는다. 기체 외부에 안테나를 장착하면 공기저항이 커져 연료 소모가 늘어나는 만큼 운항비도 증가할 수 있다.

                    해외 LCC들도 스타링크 도입에 신중한 모습이다. 유럽 최대 LCC 라이언에어는 1시간 안팎의 짧은 비행시간과 비용 부담 등을 이유로 스타링크를 도입하지 않기로 했다. 라이언에어는 안테나 장착으로 연료 효율이 약 2% 떨어지고 설치비를 포함해 연간 2억5000만달러(약 3600억원)의 비용이 들 것으로 내다봤다

                    LCC의 높은 항공기 리스 비중도 변수다. 스타링크는 기체 외부에 안테나를 설치해야 해 리스사와 별도 협의가 필요하고 계약 조건에 따라 기체 개조 승인이나 반납 시 원상복구 비용 등이 추가될 가능성도 있다. 낮은 운임과 비용 효율화로 수익성을 확보하는 LCC 특성상 이 같은 추가 비용이 수익성을 더욱 압박할 수 있다는 분석이다.

                    LCC 관계자는 "무료 기내 와이파이 서비스가 확대되면 소비자들의 눈높이는 자연스럽게 높아질 것"이라면서도 "비용 부담이 큰 만큼 도입을 쉽게 결정하기는 어렵다"고 말했다. "스타링크 외에 다른 와이파이 시스템을 비롯해 기내 서비스 품질을 높일 수 있는 다양한 방안을 검토하고 있다"고 덧붙였다.
                """
    },
    {
        "title" : "‘올공’ 시위서 경찰에 침 뱉은 40대女, 법정서 ‘눈물 호소’",
        "text" : """
                    서울 송파구 올림픽공원 잠실 개표소 시위 현장에서 다른 참가자와 경찰관을 폭행하거나 모욕한 혐의로 구속기소된 40대 여성이 법정에서 범행을 인정하며 눈물로 선처를 호소했다.

                    서울동부지법 형사9단독 이지민 판사는 29일 공무집행방해 등 혐의로 기소된 김모씨(45)에 대한 공판을 열었다. 재판부는 “피고인이 반성문을 제출했다”며 피해자 가운데 2명은 합의할 의사가 없다는 뜻을 밝혔고 1명은 회신하지 않았다고 설명했다.

                    김씨는 지난 6월22~23일 개표소 시위 현장에서 다른 시위 참가자에게 시비를 걸어 폭행하고, 이를 제지하는 참가자와 경찰관에게 모욕적인 말을 하거나 침을 뱉은 혐의를 받는다.

                    순찰 중이던 경찰관에게 “중국 경찰 아니냐”고 물으며 촬영하려 한 뒤 제지를 받자 경찰관 얼굴에 두 차례 침을 뱉어 공무집행을 방해한 혐의도 있다. 피해자는 경찰관과 시위 참가자 등 모두 5명으로 파악됐다.

                    김씨는 7월7일 개표소 시위 참가자 가운데 처음으로 구속기소됐다. 검찰은 지난 8일 열린 첫 공판에서 “경찰관을 폭행하고 모욕했으며 일면식도 없는 다른 시위자를 폭행했다”며 징역 2년을 구형했다.

                    김씨는 구속 전 피의자 심문 당시에는 “경찰한테 폭행도 당했고 목도 졸렸다”며 억울함을 주장했으나 재판이 시작된 뒤에는 범행을 인정하고 반성한다는 입장을 밝혔다. 앞서 경찰은 김씨를 공무집행방해 혐의로 구속 송치했다.

                    이날 김씨는 A4용지 2~3장 분량의 반성문을 읽으며 “준법정신에 어긋나는 행동을 해 사회적으로 큰 물의를 일으킨 점을 너무 죄송하게 생각한다. 정말 잘못했다”고 말했다.

                    이어 “개인적인 선입견과 오해로 절대 해서는 안 되는 폭력 행위를 해 피해자에게 큰 수치를 느끼게 했다”며 “다시는 어떤 상황에서도 타인에게 상처를 줄 수 있는 말과 행동을 하지 않겠다”고 흐느꼈다.

                    김씨에 대한 선고공판은 다음 달 27일 열릴 예정이다.
                """
    },
    {
        "title" : "'작은 실천이 생명 구할 수 있어' 17년간 200회 헌혈한 군무원",
        "text" : """
                    육군 제35보병사단은 전북 남원시 백마여단 예비군훈련대에서 근무하는 군무원 송호선(35)씨가 헌혈 200회를 달성했다고 29일 밝혔다.

                    송씨는 전날 아버지 송태규 씨와 함께 200번째 헌혈에 참여했다.

                    이날은 송씨의 딸이 태어난 지 1천일이 되는 날이어서 가족에게 더욱 특별한 기념일이 됐다.

                    송씨의 아버지 역시 이날 423번째 헌혈을 했다.

                    또 아내는 40회, 누이는 141회 헌혈하는 등 송씨 본인을 포함한 가족의 누적 헌혈 횟수는 800회를 넘어섰다.

                    과거 육군 대위로 복무한 송씨는 2009년 처음 헌혈을 시작해 2017년에는 헌혈 100회를 달성했다.

                    이후에도 그는 체력과 건강을 관리하면서 꾸준히 헌혈을 이어오고 있다.

                    송씨는 "헌혈은 작은 실천으로 누군가의 생명을 살릴 수 있는 직접적인 나눔"이라며 "앞으로도 건강관리를 꾸준히 하면서 헌혈을 이어가겠다"고 말했다.
                """
    }
]

for article in news:
    print(article["title"])
    article["text"] = " ".join(article["text"].split())

커피 효과, 카페인 때문만 아니었다…디카페인 마셔도 나타난 변화
악어 잡아먹는 뱀 사냥 대회…1등은 60마리 잡아
[속보]배드민턴 이소희·백하나, 24년 만에 여자 복식 금빛 스매시
“한강=치킨” 공식 깨졌다…요즘 대세는 ‘회’
LG전자, AI·로봇 사업 호조… 3분기 영업이익 37% 증가
“더 높은 금리 찾아줘” AI 은행 예금 빼갈까
교황도 'AI 위협론' 힘 실었다…"역겨운 음모"라는 트럼프 주장에 정면 반박
대형사 스타링크 무료 와이파이 경쟁, LCC는 속앓이
‘올공’ 시위서 경찰에 침 뱉은 40대女, 법정서 ‘눈물 호소’
'작은 실천이 생명 구할 수 있어' 17년간 200회 헌혈한 군무원

In [8]:
k = Komoran()
for article in news:
    print(k.pos(article["text"]))

[('커피', 'NNG'), ('가', 'JKS'), ('장내', 'NNG'), ('미생물', 'NNP'), ('과', 'JC'), ('기분', 'NNG'), (',', 'SP'), ('인지', 'NNP'), ('기능', 'NNG'), ('에', 'JKB'), ('미치', 'VV'), ('는', 'ETM'), ('영향', 'NNG'), ('이', 'JKS'), ('카페인', 'NNP'), ('때문', 'NNB'), ('만', 'JX'), ('은', 'JX'), ('아니', 'VCN'), ('ㄹ', 'ETM'), ('수', 'NNB'), ('있', 'VV'), ('다는', 'ETM'), ('연구', 'NNG'), ('결과', 'NNG'), ('가', 'JKS'), ('나오', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('카페인', 'NNP'), ('이', 'JKS'), ('들', 'VV'), ('ㄴ', 'ETM'), ('커피', 'NNG'), ('뿐', 'JX'), ('아니', 'VCN'), ('라', 'EC'), ('디카페인 커피', 'NNP'), ('를', 'JKO'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('사람', 'NNG'), ('에게서', 'JKB'), ('도', 'JX'), ('장내', 'NNG'), ('미생물', 'NNP'), ('과', 'JC'), ('일부', 'NNG'), ('심리', 'NNG'), ('·', 'SP'), ('인지', 'NNP'), ('지표', 'NNG'), ('에', 'JKB'), ('변화', 'NNG'), ('가', 'JKS'), ('나타나', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('최근', 'NNG'), ('과학', 'NNG'), ('전문', 'NNG'), ('매체', 'NNG'), ('들', 'XSN'), ('은', 'JX'), ('커피', 'NNP'), ('섭취', 'NNP'), ('가', 'JKS'), ('장내', 'NNG'), ('미생물', 'NNP'), ('과', 'JC'), ('뇌', 'NNG'), ('기능', 'NNG'), ('사이', 'NNG'), ('의', 'JKG'), ('관계', 'NNG'), ('에', 'JKB'), ('미치', 'VV'), ('는', 'ETM'), ('영향', 'NNG'), ('을', 'JKO'), ('분석', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('연구', 'NNG'), ('를', 'JKO'), ('소개', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('연구', 'NNG'), ('는', 'JX'), ('아일랜드', 'NNP'), ('코크', 'NNP'), ('대', 'NNB'), ('(', 'SS'), ('UCC', 'SL'), (')', 'SS'), ('산하', 'NNP'), ('APC', 'SL'), ('마이크로', 'NNP'), ('바', 'NNB'), ('이', 'VCP'), ('오', 'EP'), ('ㅁ', 'ETN'), ('아일랜드', 'NNP'), ('연구진', 'NNG'), ('등', 'NNB'), ('이', 'JKS'), ('진행', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('으며', 'EC'), ('국제', 'NNG'), ('학술지', 'NNP'), ("'", 'SS'), ('네이처', 'NNP'), ("커뮤니케이션즈'에", 'NA'), ('게재', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('다', 'EF'), ('.', 'SF'), ('연구진', 'NNG'), ('은', 'JX'), ('커피', 'NNG'), ('가', 'JKS'), ('장내', 'NNG'), ('미생물', 'NNP'), ('과', 'JC'), ('뇌', 'NNG'), ('사이', 'NNG'), ('의', 'JKG'), ('양', 'MM'), ('방향', 'NNP'), ('소통', 'NNP'), ('체계', 'NNG'), ('이', 'VCP'), ('ㄴ', 'ETM'), ("'", 'SS'), ('마이크로', 'NNP'), ('바이오', 'NNP'), ('타', 'NNG'), ('-', 'SS'), ('장', 'NNP'), ('-', 'SS'), ('뇌', 'NNG'), ('축', 'NNG'), ("'", 'SS'), ('에', 'JKB'), ('어떤', 'MM'), ('영향', 'NNG'), ('을', 'JKO'), ('미치', 'VV'), ('는지', 'EC'), ('알아보', 'VV'), ('기', 'ETN'), ('위하', 'VV'), ('아', 'EC'), ('30', 'SN'), ('~', 'SO'), ('50', 'SN'), ('세', 'NNB'), ('건강', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('성인', 'NNG'), ('62', 'SN'), ('명', 'NNB'), ('을', 'JKO'), ('조사', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('이', 'MM'), ('가운데', 'NNG'), ('31', 'SN'), ('명', 'NNB'), ('은', 'JX'), ('평소', 'NNG'), ('커피', 'NNG'), ('를', 'JKO'), ('마시', 'VV'), ('지', 'EC'), ('않', 'VX'), ('았', 'EP'), ('고', 'EC'), ('나머지', 'NNG'), ('31', 'SN'), ('명', 'NNB'), ('은', 'JX'), ('하루', 'NNG'), ('3', 'SN'), ('~', 'SO'), ('5', 'SN'), ('잔', 'NNG'), ('을', 'JKO'), ('마시', 'VV'), ('는', 'ETM'), ('사람', 'NNG'), ('들', 'XSN'), ('이', 'VCP'), ('었', 'EP'), ('다', 'EF'), ('.', 'SF'), ('연구진', 'NNG'), ('은', 'JX'), ('이', 'NP'), ('들', 'XSN'), ('의', 'JKG'), ('장내', 'NNG'), ('미생물', 'NNP'), ('과', 'JC'), ('대사', 'NNG'), ('산물', 'NNG'), (',', 'SP'), ('인지', 'NNP'), ('기능', 'NNG'), (',', 'SP'), ('기분', 'NNG'), ('과', 'JC'), ('스트레스', 'NNP'), ('등', 'NNB'), ('을', 'JKO'), ('비교', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('분석', 'NNG'), ('결과', 'NNG'), ('평소', 'NNG'), ('커피', 'NNG'), ('를', 'JKO'), ('마시', 'VV'), ('는', 'ETM'), ('사람', 'NNG'), ('과', 'JC'), ('마시', 'VV'), ('지', 'EC'), ('않', 'VX'), ('는', 'ETM'), ('사람', 'NNG'), ('사이에서', 'NNP'), ('는', 'JX'), ('장내', 'NNG'), ('미생물', 'NNP'), ('구성', 'NNG'), ('에', 'JKB'), ('차이', 'NNG'), ('가', 'JKS'), ('나타나', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('커피', 'NNP'), ('섭취', 'NNP'), ('자', 'NNB'), ('에게서', 'JKB'), ('는', 'JX'), ('크립토박테리움(Cryptobacterium)과', 'NA'), ('에', 'NNG'), ('거', 'NNB'), ('텔', 'NNP'), ('이', 'VCP'), ('라', 'EC'), ('(', 'SS'), ('Eggerthella', 'SL'), (')', 'SS'), ('등', 'NNB'), ('일부', 'NNG'), ('미생물', 'NNP'), ('의', 'JKG'), ('상대', 'NNG'), ('적', 'XSN'), ('비율', 'NNG'), ('이', 'JKS'), ('높', 'VA'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('장내', 'NNG'), ('미생물', 'NNP'), ('이', 'JKS'), ('만들', 'VV'), ('어', 'EC'), ('내', 'VX'), ('는', 'ETM'), ('일부', 'NNG'), ('대사', 'NNG'), ('산물', 'NNG'), ('에서', 'JKB'), ('도', 'JX'), ('차이', 'NNG'), ('가', 'JKS'), ('나타나', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('커피', 'NNP'), ('섭취', 'NNP'), ('자', 'NNB'), ('는', 'JX'), ('인', 'NNG'), ('돌', 'NNP'), ('-3', 'NNP'), ('-', 'SS'), ('프로피온산', 'NNP'), ('과', 'JC'), ('인돌-3-카르복스알데히드,', 'NA'), ('신경전달물질', 'NNP'), ('이', 'VCP'), ('ㄴ', 'ETM'), ('감마', 'NNP'), ('아미', 'NNP'), ('노', 'NNP'), ('부', 'NNB'), ('티르', 'NNP'), ('산', 'NNG'), ('(', 'SS'), ('GABA', 'SL'), (')', 'SS'), ('수치', 'NNG'), ('가', 'JKS'), ('상대', 'NNG'), ('적', 'XSN'), ('으로', 'JKB'), ('낮', 'VA'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('연구진', 'NNG'), ('은', 'JX'), ('여기', 'NP'), ('서', 'JKB'), ('한', 'MM'), ('단계', 'NNG'), ('더', 'MAG'), ('나아가', 'VV'), ('아', 'EC'), ('커피', 'NNG'), ('를', 'JKO'), ('끊', 'VV'), ('었', 'EP'), ('다가', 'EC'), ('다시', 'MAG'), ('마시', 'VV'), ('게', 'EC'), ('하', 'VV'), ('는', 'ETM'), ('실험', 'NNG'), ('을', 'JKO'), ('진행', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('평소', 'NNG'), ('하루', 'NNG'), ('3', 'SN'), ('~', 'SO'), ('5', 'SN'), ('잔', 'NNP'), ('의', 'JKG'), ('커피', 'NNG'), ('를', 'JKO'), ('마시', 'VV'), ('던', 'ETM'), ('참가자', 'NNG'), ('31', 'SN'), ('명', 'NNB'), ('에게', 'JKB'), ('2', 'SN'), ('주', 'NNB'), ('동안', 'NNG'), ('커피', 'NNG'), ('와', 'JC'), ('카페인', 'NNP'), ('을', 'JKO'), ('섭취', 'NNG'), ('하', 'XSV'), ('지', 'EC'), ('않', 'VX'), ('도록', 'EC'), ('하', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('이후', 'NNG'), ('이', 'NP'), ('들', 'XSN'), ('을', 'JKO'), ('무작위', 'NNP'), ('로', 'JKB'), ('나누', 'VV'), ('어', 'EC'), ('16', 'SN'), ('명', 'NNB'), ('에게', 'JKB'), ('는', 'JX'), ('카페인', 'NNP'), ('이', 'JKS'), ('들', 'VV'), ('ㄴ', 'ETM'), ('커피', 'NNG'), ('를', 'JKO'), (',', 'SP'), ('15', 'SN'), ('명', 'NNB'), ('에게', 'JKB'), ('는', 'JX'), ('디카페인 커피', 'NNP'), ('를', 'JKO'), ('3', 'SN'), ('주', 'NNB'), ('동안', 'NNG'), ('하루', 'NNG'), ('네', 'MM'), ('차례', 'NNG'), ('마시', 'VV'), ('게', 'EC'), ('하', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('그', 'MM'), ('결과', 'NNG'), ('커피', 'NNG'), ('를', 'JKO'), ('다시', 'MAG'), ('마시기', 'NNP'), ('시작', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('뒤', 'NNG'), ('장내', 'NNG'), ('미생물', 'NNP'), ('구성', 'NNG'), ('에', 'JKB'), ('변화', 'NNG'), ('가', 'JKS'), ('나타나', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('특히', 'MAG'), ('일부', 'NNG'), ('변화', 'NNG'), ('는', 'JX'), ('카페인', 'NNP'), ('커피', 'NNG'), ('를', 'JKO'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('집단', 'NNG'), ('과', 'JC'), ('디카페인 커피', 'NNP'), ('를', 'JKO'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('집단', 'NNG'), ('에서', 'JKB'), ('모두', 'MAG'), ('관찰', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('다', 'EF'), ('.', 'SF'), ('연구진', 'NNG'), ('은', 'JX'), ('이', 'NP'), ('를', 'JKO'), ('근거', 'NNG'), ('로', 'JKB'), ('커피', 'NNG'), ('가', 'JKS'), ('장내', 'NNG'), ('환경', 'NNG'), ('에', 'JKB'), ('미치', 'VV'), ('는', 'ETM'), ('영향', 'NNG'), ('을', 'JKO'), ('카페인', 'NNP'), ('만', 'NNB'), ('으로', 'JKB'), ('설명', 'NNG'), ('하', 'XSV'), ('기', 'ETN'), ('는', 'JX'), ('어렵', 'VA'), ('다고', 'EC'), ('보', 'VV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('커피', 'NNG'), ('에', 'JKB'), ('는', 'JX'), ('카페인', 'NNP'), ('외', 'NNB'), ('에', 'JKB'), ('도', 'JX'), ('폴리페놀', 'NNP'), ('을', 'JKO'), ('비롯', 'XR'), ('하', 'XSA'), ('아', 'EC'), ('장내', 'NNG'), ('미생물', 'NNP'), ('과', 'JC'), ('상호작용', 'NNP'), ('하', 'XSA'), ('ㄹ', 'ETM'), ('수', 'NNB'), ('있', 'VV'), ('는', 'ETM'), ('다양', 'XR'), ('하', 'XSA'), ('ㄴ', 'ETM'), ('생리', 'NNG'), ('활성', 'NNG'), ('성분', 'NNG'), ('이', 'JKS'), ('들', 'VV'), ('어', 'EC'), ('있', 'VV'), ('기', 'ETN'), ('때문', 'NNB'), ('이', 'VCP'), ('다', 'EF'), ('.', 'SF'), ('기분', 'NNG'), ('과', 'JC'), ('인지', 'NNP'), ('기능', 'NNG'), ('을', 'JKO'), ('측정', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('결과', 'NNG'), ('에서', 'JKB'), ('도', 'JX'), ('카페인', 'NNP'), ('여부', 'NNG'), ('에', 'JKB'), ('따르', 'VV'), ('아', 'EC'), ('서로', 'MAG'), ('다른', 'MM'), ('변화', 'NNG'), ('가', 'JKS'), ('관찰', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('다', 'EF'), ('.', 'SF'), ('커피', 'NNG'), ('를', 'JKO'), ('다시', 'MAG'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('뒤', 'NNG'), ('카페인', 'NNP'), ('커피', 'NNG'), ('와', 'JC'), ('디카페인 커피', 'NNP'), ('를', 'JKO'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('참가자', 'NNG'), ('모두', 'NNG'), ('에서', 'JKB'), ('주관', 'NNG'), ('적', 'XSN'), ('으로', 'JKB'), ('느끼', 'VV'), ('는', 'ETM'), ('스트레스', 'NNP'), ('와', 'JC'), ('우울', 'NNP'), ('증상', 'NNP'), (',', 'SP'), ('충동', 'NNG'), ('성', 'XSN'), ('지표', 'NNG'), ('가', 'JKS'), ('감소', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('카페인', 'NNP'), ('커피', 'NNG'), ('를', 'JKO'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('집단', 'NNG'), ('에서', 'JKB'), ('는', 'JX'), ('불안', 'NNG'), ('과', 'JC'), ('심리', 'NNG'), ('적', 'XSN'), ('스트레스', 'NNG'), ('가', 'JKS'), ('감소', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('반면', 'NNG'), ('디카페인 커피', 'NNP'), ('를', 'JKO'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('집단', 'NNG'), ('에서', 'JKB'), ('는', 'JX'), ('일부', 'NNG'), ('기억', 'NNG'), ('검사', 'NNG'), ('결과', 'NNG'), ('와', 'JC'), ('수면', 'NNP'), ('관련', 'NNG'), ('지표', 'NNG'), ('가', 'JKS'), ('개선', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('다', 'EF'), ('.', 'SF'), ('이', 'NP'), ('는', 'JX'), ('커피', 'NNG'), ('를', 'JKO'), ('마시', 'VV'), ('ㄴ', 'ETM'), ('뒤', 'NNG'), ('나타나', 'VV'), ('는', 'ETM'), ('변화', 'NNG'), ('가', 'JKS'), ('반드시', 'MAG'), ('카페인', 'NNP'), ('섭취', 'NNP'), ('에서', 'JKB'), ('만', 'JX'), ('비롯', 'XR'), ('되', 'XSV'), ('는', 'ETM'), ('것', 'NNB'), ('은', 'JX'), ('아니', 'VCN'), ('ㄹ', 'ETM'), ('가능', 'XR'), ('성', 'XSN'), ('을', 'JKO'), ('보이', 'VV'), ('어', 'EC'), ('주', 'VX'), ('ㄴ다', 'EF'), ('.', 'SF'), ('연구진', 'NNG'), ('은', 'JX'), ('카페인', 'NNP'), ('이외', 'NNG'), ('의', 'JKG'), ('커피', 'NNP'), ('성분', 'NNG'), ('이', 'JKS'), ('장내', 'NNG'), ('미생물', 'NNG'), ('을', 'JKO'), ('변화', 'NNG'), ('시키', 'XSV'), ('고', 'EC'), (',', 'SP'), ('이', 'MM'), ('같', 'VA'), ('은', 'ETM'), ('변화', 'NNG'), ('가', 'JKS'), ('장과', 'NNP'), ('뇌', 'NNG'), ('사이', 'NNG'), ('의', 'JKG'), ('상호작용', 'NNP'), ('에', 'JKB'), ('관여', 'NNG'), ('하', 'XSV'), ('ㄹ', 'ETM'), ('가능', 'XR'), ('성', 'XSN'), ('에', 'JKB'), ('주목', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('다만', 'MAJ'), ('이번', 'NNG'), ('연구', 'NNG'), ('만', 'JX'), ('으로', 'JKB'), ('디카페인 커피', 'NNP'), ('가', 'JKS'), ('기억력', 'NNG'), ('을', 'JKO'), ('높이', 'VV'), ('거나', 'EC'), ('우울', 'NNP'), ('·', 'SP'), ('스트레스', 'NNP'), ('를', 'JKO'), ('줄이', 'VV'), ('ㄴ다고', 'EC'), ('단정', 'XR'), ('하', 'XSA'), ('ㄹ', 'ETM'), ('수', 'NNB'), ('는', 'JX'), ('없', 'VA'), ('다', 'EF'), ('.', 'SF'), ('커피', 'NNG'), ('를', 'JKO'), ('끊', 'VV'), ('었', 'EP'), ('다가', 'EC'), ('다시', 'MAG'), ('마시', 'VV'), ('는', 'ETM'), ('실험', 'NNG'), ('에', 'JKB'), ('참여', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('사람', 'NNG'), ('이', 'JKS'), ('31', 'SN'), ('명', 'NNB'), ('에', 'JKB'), ('불과', 'XR'), ('하', 'XSA'), ('고', 'EC'), (',', 'SP'), ('장내', 'NNG'), ('미생물', 'NNP'), ('변화', 'NNG'), ('와', 'JC'), ('심리', 'NNG'), ('·', 'SP'), ('인지', 'NNP'), ('기능', 'NNG'), ('변화', 'NNG'), ('사이', 'NNG'), ('의', 'JKG'), ('직접', 'NNG'), ('적', 'XSN'), ('이', 'VCP'), ('ㄴ', 'ETM'), ('인과관계', 'NNP'), ('도', 'JX'), ('확인', 'NNG'), ('되', 'XSV'), ('지', 'EC'), ('않', 'VX'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('연구진', 'NNG'), ('은', 'JX'), ('향후', 'NNG'), ('더', 'MAG'), ('많', 'VA'), ('은', 'ETM'), ('사람', 'NNG'), ('을', 'JKO'), ('대상', 'NNG'), ('으로', 'JKB'), ('장기간', 'NNG'), ('연구', 'NNG'), ('를', 'JKO'), ('진행', 'NNG'), ('하', 'XSV'), ('아', 'EC'), ('커피', 'NNP'), ('속', 'NNG'), ('어떤', 'MM'), ('성분', 'NNG'), ('이', 'JKS'), ('장내', 'NNG'), ('미생물', 'NNP'), ('에', 'JKB'), ('영향', 'NNG'), ('을', 'JKO'), ('주', 'VX'), ('고', 'EC'), (',', 'SP'), ('이러', 'XR'), ('하', 'XSA'), ('ㄴ', 'ETM'), ('변화', 'NNG'), ('가', 'JKS'), ('뇌', 'NNG'), ('와', 'JC'), ('행동', 'NNG'), ('에', 'JKB'), ('어떤', 'MM'), ('영향', 'NNG'), ('을', 'JKO'), ('미치', 'VV'), ('는지', 'EC'), ('확인', 'NNG'), ('하', 'XSV'), ('ㄹ', 'ETM'), ('필요', 'NNG'), ('가', 'JKS'), ('있', 'VV'), ('다고', 'EC'), ('설명', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF')]
[('미국', 'NNP'), ('플로리다주', 'NNP'), ('에서', 'JKB'), ('뱀', 'NNG'), ('사냥', 'NNP'), ('대회', 'NNG'), ('가', 'JKS'), ('열리', 'VV'), ('ㄴ다', 'EF'), ('.', 'SF'), ('대상', 'NNG'), ('은', 'JX'), ('버마', 'NNP'), ('왕뱀', 'NNP'), ('(', 'SS'), ('버마비단뱀', 'NNP'), (')', 'SS'), ('이', 'VCP'), ('다', 'EF'), ('.', 'SF'), ('원산지', 'NNG'), ('는', 'JX'), ('동남아시아', 'NNP'), ('지만', 'NNP'), ('애완동물', 'NNP'), ('거래', 'NNG'), ('를', 'JKO'), ('통하', 'VV'), ('아', 'EC'), ('플로리다', 'NNP'), ('에', 'JKB'), ('들어오', 'VV'), ('았', 'EP'), ('고', 'EC'), ('일부', 'NNG'), ('가', 'JKS'), ('야생', 'NNG'), ('으로', 'JKB'), ('퍼지', 'VV'), ('었', 'EP'), ('다', 'EF'), ('.', 'SF'), ('암컷', 'NNP'), ('한', 'MM'), ('마리', 'NNB'), ('는', 'JX'), ('한', 'MM'), ('번', 'NNB'), ('에', 'JKB'), ('50', 'SN'), ('~', 'SO'), ('100', 'SN'), ('개', 'NNB'), ('의', 'JKG'), ('알', 'VV'), ('을', 'ETM'), ('낳', 'VV'), ('는다', 'EF'), ('.', 'SF'), ('천적', 'NNP'), ('이', 'JKS'), ('거의', 'MAG'), ('없', 'VA'), ('고', 'EC'), ('번식력', 'NNG'), ('이', 'JKS'), ('매우', 'MAG'), ('높', 'VA'), ('아', 'EC'), ('개체', 'NNP'), ('수', 'NNB'), ('가', 'JKS'), ('급증', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('버마', 'NNP'), ('왕뱀', 'NNP'), ('은', 'JX'), ('토끼', 'NNG'), ('나', 'JC'), ('새', 'VV'), ('는', 'ETM'), ('물론', 'MAG'), (',', 'SP'), ('사슴', 'NNP'), ('이나', 'JC'), ('악어', 'NNP'), ('까지', 'JX'), ('잡아먹', 'VV'), ('는', 'ETM'), ('최상위 포식자', 'NNP'), ('다', 'EF'), ('.', 'SF'), ('일부', 'NNG'), ('포유류', 'NNP'), ('개체', 'NNP'), ('수', 'NNB'), ('가', 'JKS'), ('90', 'SN'), ('%', 'SW'), ('이상', 'NNG'), ('감소', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('지역', 'NNG'), ('이', 'JKS'), ('보고', 'NNG'), ('되', 'XSV'), ('ㄹ', 'ETM'), ('정도', 'NNG'), ('로', 'JKB'), ('토착', 'NNG'), ('생태계', 'NNP'), ('가', 'JKS'), ('크', 'VA'), ('게', 'EC'), ('교란', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('다', 'EF'), ('.', 'SF'), ('잡히', 'VV'), ('ㄴ', 'ETM'), ('버마', 'NNP'), ('왕뱀', 'NNP'), ('은', 'JX'), ('평균', 'NNG'), ('길', 'NNG'), ('이', 'JKS'), ('180', 'SN'), ('~', 'SO'), ('270', 'SN'), ('cm', 'SW'), (',', 'SP'), ('가장', 'MAG'), ('크', 'VA'), ('ㄴ', 'ETM'), ('것', 'NNB'), ('은', 'JX'), ('580', 'SN'), ('cm', 'SW'), ('다', 'JX'), ('.', 'SF'), ('전문가', 'NNG'), ('들', 'XSN'), ('은', 'JX'), ('완전', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('박멸', 'NNG'), ('은', 'JX'), ('사실', 'NNG'), ('상', 'XSN'), ('불가', 'NNG'), ('하', 'XSV'), ('지만', 'EC'), (',', 'SP'), ('지속', 'NNG'), ('적', 'XSN'), ('이', 'VCP'), ('ㄴ', 'ETM'), ('포획', 'NNG'), ('이', 'JKS'), ('피해', 'NNG'), ('를', 'JKO'), ('줄이', 'VV'), ('는', 'ETM'), ('데', 'NNB'), ('중요', 'XR'), ('하', 'XSA'), ('다고', 'EC'), ('보', 'VX'), ('ㄴ다', 'EF'), ('.', 'SF'), ('이', 'NP'), ('에', 'JKB'), ('주', 'NNG'), ('정부', 'NNG'), ('는', 'JX'), ("'", 'SS'), ('파이', 'NNP'), ('톤', 'NNB'), ('(', 'SS'), ('비단', 'NNP'), ('뱀', 'NNG'), (')', 'SS'), ('채', 'VV'), ('ㄹ', 'ETM'), ('린지', 'NNP'), ('Python', 'SL'), ('Challenge', 'SL'), ("'", 'SS'), ('를', 'JKO'), ('7월', 'NNP'), ('열흘', 'NNG'), ('간', 'NNB'), ('개최', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF'), ('참가자', 'NNG'), ('는', 'JX'), ('온라인', 'NNG'), ('교육', 'NNG'), ('을', 'JKO'), ('받', 'VV'), ('고', 'EC'), ('시험', 'NNG'), ('을', 'JKO'), ('치', 'VV'), ('어야', 'EC'), ('하', 'VX'), ('ㄴ다', 'EF'), ('.', 'SF'), ('참가비', 'NNG'), ('는', 'JX'), ('25', 'SN'), ('달러', 'NNB'), ('이', 'VCP'), ('다', 'EF'), ('.', 'SF'), ('총', 'MM'), ('상금', 'NNG'), ('은', 'JX'), ('2', 'SN'), ('만', 'NR'), ('5', 'SN'), (',', 'SP'), ('000', 'SN'), ('달러', 'NNB'), ('(', 'SS'), ('3', 'SN'), (',', 'SP'), ('500', 'SN'), ('만', 'NR'), ('원', 'NNB'), (')', 'SS'), (',', 'SP'), ('가장', 'MAG'), ('많', 'VA'), ('은', 'ETM'), ('뱀', 'NNG'), ('을', 'JKO'), ('잡', 'VV'), ('은', 'ETM'), ('사람', 'NNG'), ('에게', 'JKB'), ('는', 'JX'), ('1', 'SN'), ('만', 'NR'), ('달러', 'NNB'), ('(', 'SS'), ('1', 'SN'), (',', 'SP'), ('400', 'SN'), ('만', 'NR'), ('원', 'NNB'), (')', 'SS'), ('가', 'JKS'), ('지급', 'NNG'), ('되', 'XSV'), ('ㄴ다', 'EF'), ('.', 'SF'), ('총기', 'NNG'), ('사용', 'NNG'), ('은', 'JX'), ('금지', 'NNG'), ('되', 'XSV'), ('며', 'EC'), (',', 'SP'), ('동물', 'NNP'), ('복지', 'NNP'), ('기준', 'NNG'), ('에', 'JKB'), ('맞', 'VV'), ('는', 'ETM'), ('인도', 'NNG'), ('적', 'XSN'), ('이', 'VCP'), ('ㄴ', 'ETM'), ('포획', 'NNG'), ('·', 'SP'), ('안락사', 'NNP'), ('가', 'JKS'), ('의무', 'NNP'), ('다', 'EF'), ('.', 'SF'), ('현지', 'NNG'), ('기사', 'NNG'), ('는', 'JX'), ('"', 'SS'), ('이', 'MM'), ('대회', 'NNG'), ('가', 'JKS'), ('단순', 'XR'), ('하', 'XSA'), ('ㄴ', 'ETM'), ('이색', 'NNP'), ('이벤트', 'NNP'), ('가', 'JKS'), ('아니', 'VCN'), ('라', 'EC'), (',', 'SP'), ("'", 'SS'), ('시민', 'NNP'), ('참여', 'NNG'), ('를', 'JKO'), ('통하', 'VV'), ('ㄴ', 'ETM'), ('생태계', 'NNP'), ('보전', 'NNG'), (',', 'SP'), ('외래종', 'NNG'), ('문제', 'NNG'), ('에', 'JKB'), ('대하', 'VV'), ('ㄴ', 'ETM'), ('대중', 'NNP'), ('인식', 'NNG'), ('제고', 'NNG'), (',', 'SP'), ('실제', 'NNG'), ('개체', 'NNP'), ('수', 'NNB'), ('관리', 'NNG'), ("'", 'SS'), ('이', 'VCP'), ('라는', 'ETM'), ('세', 'MM'), ('가지', 'NNB'), ('목적', 'NNG'), ('을', 'JKO'), ('동시', 'NNG'), ('에', 'JKB'), ('갖', 'VV'), ('고', 'EC'), ('있다', 'NNP'), ('"', 'SS'), ('이', 'VCP'), ('며', 'EC'), ('"', 'SS'), ('다만', 'NNP'), ('버마', 'NNP'), ('왕뱀', 'NNP'), ('이', 'JKS'), ('수', 'NNB'), ('만', 'JX'), ('마리', 'NNB'), ('이상', 'NNG'), ('이', 'VCP'), ('어서', 'EC'), (',', 'SP'), ('이', 'MM'), ('대회', 'NNG'), ('만', 'JX'), ('으로', 'JKB'), ('문제', 'NNG'), ('를', 'JKO'), ('해결', 'NNG'), ('하', 'XSV'), ('ㄹ', 'ETM'), ('수', 'NNB'), ('는', 'JX'), ('없', 'VA'), ('다', 'EC'), ('"', 'SS'), ('고', 'JKQ'), ('지적', 'NNG'), ('하', 'XSV'), ('았', 'EP'), ('다', 'EF'), ('.', 'SF')]
[('한국', 'NNP'), ('배드민턴', 'NNP'), ('여자', 'NNG'), ('복식', 'NNG'), ('의', 'JKG'), ('간판', 'NNP'), ('이', 'MM'), ('소희', 'NNP'), ('-', 'SS'), ('백', 'NR'), ('하나', 'NR'), ('조가', 'NNP'), ('2026', 'SN'), ('아이치', 'NNP'), ('·', 'SP'), ('나고야', 'NNP'), ('아시안게임', 'NNG'), ('에서', 'JKB'), ('금메달', 'NNG'), ('을', 'JKO'), ('목', 'NNG'), ('에', 'JKB'), ('걷', 'VV'), ('었', 'EP'), ('습니다', 'EF'), ('.', 'SF'), ('세계', 'NNG'), ('랭킹', 'NNG'), ('2', 'SN'), ('위', 'NNB'), ('이', 'VCP'), ('ㄴ', 'ETM'), ('이', 'MM'), ('소희', 'NNP'), ('-', 'SS'), ('백', 'NR'), ('하나', 'NR'), ('조', 'NNB'), ('는', 'JX'), ('29', 'SN'), ('일', 'NNB'), ('일본', 'NNP'), ('아이', 'NNG'), ('이치현', 'NNP'), ('이치노미야 시', 'NNP'), ('립', 'NNG'), ('체육관', 'NNP'), ('에서', 'JKB'), ('열리', 'VV'), ('ㄴ', 'ETM'), ('대회', 'NNG'), ('배드민턴', 'NNP'), ('여자', 'NNG'), ('복식', 'NNG'), ('결승전', 'NNP'), ('에서', 'JKB'), ('세계', 'NNG'), ('랭킹', 'NNG'), ('1', 'SN'), ('위', 'NNB'), ('이', 'VCP'), ('ㄴ', 'ETM'), ('중국', 'NNP'), ('의', 'JKG'), ('류성수-탄닝', 'NA'), ('조', 'NNG'), ('를', 'JKO'), ('상대로', 'NNP'), ('2', 'SN'), ('-1', 'NNP'), ('(', 'SS'), ('26', 'SN'), ('-', 'SW'), ('28', 'SN'), ('21', 'SN'), ('-', 'SW'), ('18', 'SN'), ('21', 'SN'), ('-', 'SW'), ('18', 'SN'), (')', 'SS'), ('역전승', 'NNG'), ('을', 'JKO'), ('거두', 'VV'), ('었', 'EP'), ('습니다', 'EF'), ('.', 'SF'), ('한국', 'NNP'), ('배드민턴', 'NNP'), ('이', 'JKS'), ('아시안게임', 'NNG'), ('여자', 'NNG'), ('복식', 'NNG'), ('에서', 'JKB'), ('정상', 'NNG'), ('에', 'JKB'), ('오르', 'VV'), ('ㄴ', 'ETM'), ('것', 'NNB'), ('은', 'JX'), ('2002', 'SN'), ('년', 'NNB'), ('부산', 'NNP'), ('대회', 'NNG'), ('라경민', 'NNP'), ('-', 'SS'), ('이경원', 'NNP'), ('조', 'NR'), ('이후', 'NNG'), ('24', 'SN'), ('년', 'NNB'), ('만', 'NNB'), ('이', 'VCP'), ('ㅂ니다', 'EF'), ('.', 'SF')]

In [30]:
USER_DIC = """
아일랜드 코크대\tNNP
마이크로바이옴\tNNP
네이처 커뮤니케이션즈\tNNP
마이크로바이오타-장-뇌 축\tNNP
크립토박테리움\tNNP
에거텔라\tNNP
인돌-3-프로피온산\tNNP
인돌-3-카르복스알데히드\tNNP
감마아미노부티르산\tNNP
폴리페놀\tNNP
버마왕뱀\tNNP
이소희\tNNP
백하나\tNNP
김나영\tNNP
한강\tNNP
노량진\tNNP
노량진 수산시장\tNNP
박강호\tNNP
블룸버그통신\tNNP
토르스텐 슬록\tNNP
아폴로글로벌매니지먼트\tNNP
레오 14세\tNNP
AP통신\tNNP
트루스소셜\tNNP
서울동부지법\tNNP
이지민\tNNP
올림픽공원\tNNP
제35보병사단\tNNP
백마여단\tNNP
송태규\tNNP
송호선\tNNP
sns\tNNG
회크닉\tNNG
이코노미스트\tNNG
뱅크런\tNNG
예비군훈련대\tNNG
"""

with open("./user_dic.txt", "w", encoding="utf-8") as f:
    f.write(USER_DIC)
    
komoran = Komoran(userdic="./user_dic.txt")

In [31]:
from collections import Counter
import numpy as np
import pandas as pd
from IPython.display import display

stopwords = {"등", "것", "수", "때", "경우", "관련", "이번", "지난"}

keep_pos = {"NNG", "NNP", "SL"}

def preprocess(text):
    if not isinstance(text, str):
        raise TypeError("기사 본문은 문자열이어야 합니다.")

    text = " ".join(text.split())

    if not text:
        return []

    return [
        word
        for word, pos in komoran.pos(text)
        if pos in keep_pos and word not in stopwords
    ]

# 각 원소가 기사 하나의 단어 목록
docs_tokens = [
    preprocess(article["text"])
    for article in news
]

doc_ids = [f"D{i:02d}" for i in range(len(news))]

doc_info = pd.DataFrame({
    "문서": doc_ids,
    "제목": [article["title"] for article in news],
    "토큰 수": [len(words) for words in docs_tokens],
})

display(doc_info)

    문서                                           제목  토큰 수
0  D00          커피 효과, 카페인 때문만 아니었다…디카페인 마셔도 나타난 변화   273
1  D01                  악어 잡아먹는 뱀 사냥 대회…1등은 60마리 잡아   105
2  D02        [속보]배드민턴 이소희·백하나, 24년 만에 여자 복식 금빛 스매시    46
3  D03                    “한강=치킨” 공식 깨졌다…요즘 대세는 ‘회’    73
4  D04           LG전자, AI·로봇 사업 호조… 3분기 영업이익 37% 증가   155
5  D05                   “더 높은 금리 찾아줘” AI 은행 예금 빼갈까   132
6  D06  교황도 'AI 위협론' 힘 실었다…"역겨운 음모"라는 트럼프 주장에 정면 반박   145
7  D07                대형사 스타링크 무료 와이파이 경쟁, LCC는 속앓이   278
8  D08          ‘올공’ 시위서 경찰에 침 뱉은 40대女, 법정서 ‘눈물 호소’   159
9  D09        '작은 실천이 생명 구할 수 있어' 17년간 200회 헌혈한 군무원    63

In [32]:
def make_tdm(documents, document_ids):
    # 전체 문서에서 사용된 고유한 단어
    vocab = sorted({
        word
        for words in documents
        for word in words
    })

    word2id = {word: i for i, word in enumerate(vocab)}

    matrix = np.zeros(
        (len(vocab), len(documents)),
        dtype=int
    )

    for doc_idx, words in enumerate(documents):
        counts = Counter(words)

        for word, count in counts.items():
            matrix[word2id[word], doc_idx] = count

    return pd.DataFrame(
        matrix,
        index=pd.Index(vocab, name="단어"),
        columns=document_ids
    )

df_TDM = make_tdm(docs_tokens, doc_ids)
df_TDM

        D00  D01  D02  D03  D04  D05  D06  D07  D08  D09
단어
-1        0    0    1    0    0    0    0    0    0    0
10대       0    0    0    0    0    0    0    1    0    0
5월        0    0    0    0    0    0    1    0    0    0
7월        0    1    0    0    0    0    0    0    0    0
9월 29일    0    0    0    0    1    0    0    0    0    0
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
회크닉       0    0    0    5    0    0    0    0    0    0
횟수        0    0    0    0    0    0    0    0    0    1
효과        0    0    0    0    0    0    0    2    0    0
효율        0    0    0    0    0    0    0    2    0    0
힐링        0    0    0    1    0    0    0    0    0    0

[736 rows x 10 columns]

* 문서 수가 고정되어 있을 때 TDM의 크기를 줄이려면 단어의 종류를 줄여야합니다.

In [35]:
tf = df_TDM.astype(float)
df = (df_TDM > 0).sum(axis=1)
N = df_TDM.shape[1]
idf = np.log(N / df)
df_TFIDF = tf.mul(idf, axis=0)

for doc_id, article in zip(doc_ids, news):
    scores = df_TFIDF[doc_id]

    top10 = (
        scores[scores > 0]
        .sort_values(ascending=False)
        .head(10)
    )

    print(f"\n[{doc_id}] {article['title']}")
    display(top10.rename("TF-IDF").to_frame())

[D00] 커피 효과, 카페인 때문만 아니었다…디카페인 마셔도 나타난 변화

            TF-IDF
단어
커피       52.959457
미생물      29.933606
장내       29.933606
카페인      27.631021
변화       23.025851
연구진      16.118096
디카페인 커피  13.815511
영향       13.815511
인지       11.512925
섭취       11.512925

[D01] 악어 잡아먹는 뱀 사냥 대회…1등은 60마리 잡아

          TF-IDF
단어
버마왕뱀    9.210340
뱀       6.907755
개체      6.907755
대회      4.828314
생태계     4.605170
이상      4.605170
포획      4.605170
문제      3.218876
Python  2.302585
교육      2.302585

[D02] [속보]배드민턴 이소희·백하나, 24년 만에 여자 복식 금빛 스매시

         TF-IDF
단어
복식     6.907755
여자     6.907755
배드민턴   6.907755
한국     4.605170
랭킹     4.605170
아시안게임  4.605170
세계     4.605170
이소희    4.605170
백하나    4.605170
대회     3.218876

[D03] “한강=치킨” 공식 깨졌다…요즘 대세는 ‘회’

        TF-IDF
단어
한강   11.512925
회크닉  11.512925
피크닉   9.210340
포장    9.210340
돗자리   4.605170
코스    4.605170
요즘    4.605170
대표    4.605170
날씨    4.605170
SNS   3.218876

[D04] LG전자, AI·로봇 사업 호조… 3분기 영업이익 37% 증가

         TF-IDF
단어
사업    18.420681
LG전자  13.815511
연구원   11.512925
로봇     9.210340
분기     9.210340
박      9.210340
추정     6.907755
영업     6.907755
수주     6.907755
전장     6.907755

[D05] “더 높은 금리 찾아줘” AI 은행 예금 빼갈까

         TF-IDF
단어
금리    16.118096
에이전트  16.118096
예금    13.815511
계좌    11.512925
AI     9.631782
은행     9.210340
대신     6.907755
금융     6.907755
이동     4.828314
돈      4.605170

[D06] 교황도 'AI 위협론' 힘 실었다…"역겨운 음모"라는 트럼프 주장에 정면 반박

        TF-IDF
단어
교황   18.420681
AI   13.243701
트럼프  11.512925
대통령   9.210340
위협    6.907755
사기    4.605170
반대    4.605170
뉴스    4.605170
일     4.605170
논의    4.605170

[D07] 대형사 스타링크 무료 와이파이 경쟁, LCC는 속앓이

         TF-IDF
단어
비용    25.328436
스타    25.328436
링크    25.328436
LCC   20.723266
와이파이  16.118096
서비스   14.484941
도입    11.512925
무료    11.512925
대한항공  11.512925
기내    11.512925

[D08] ‘올공’ 시위서 경찰에 침 뱉은 40대女, 법정서 ‘눈물 호소’

        TF-IDF
단어
김    16.118096
경찰관  13.815511
혐의   11.512925
폭행   11.512925
시위   11.512925
구속    9.210340
공무    6.907755
모욕    6.907755
방해    6.907755
개표    6.907755

[D09] '작은 실천이 생명 구할 수 있어' 17년간 200회 헌혈한 군무원

         TF-IDF
단어
헌혈    23.025851
송     13.815511
가족     4.605170
아버지    4.605170
달성     4.605170
육군     4.605170
이날     3.218876
군무원    2.302585
남원시    2.302585
건강관리   2.302585

* TDM은 여러 문서에 공통으로 자주 등장하는 단어도 높게 평가하지만 TF-IDF는 특정 문서에서 많이 나오는 단어들을 강조하는 성질을 가지고 있기 때문에 문서별로 분류하기 더 좋습니다.

In [37]:
def make_ngrams(words, n):
    return [
        tuple(words[i:i + n])
        for i in range(len(words) - n + 1)
    ]

In [38]:
docs_ngram_features = []

for words in docs_tokens:
    features = []

    for n in (1, 2, 3):
        for gram in make_ngrams(words, n):
            # 튜플 표현으로 토큰 경계도 보존
            features.append(f"{n}:{gram!r}")

    docs_ngram_features.append(features)

df_TDM_ngram = make_tdm(
    docs_ngram_features,
    doc_ids
)

print("1-gram TDM:", df_TDM.shape)
print("1~3-gram TDM:", df_TDM_ngram.shape)

top_features = (
    df_TDM_ngram.sum(axis=1)
    .sort_values(ascending=False)
    .head(20)
    .index
)

display(df_TDM_ngram.loc[top_features])

1-gram TDM: (736, 10)
1~3-gram TDM: (3372, 10)

                 D00  D01  D02  D03  D04  D05  D06  D07  D08  D09
단어
1:('커피',)         23    0    0    0    0    0    0    0    0    0
1:('AI',)          0    0    0    0    1    8   11    0    0    0
1:('미생물',)        13    0    0    0    0    0    0    0    0    0
1:('장내',)         13    0    0    0    0    0    0    0    0    0
1:('카페인',)        12    0    0    0    0    0    0    0    0    0
2:('장내', '미생물')   12    0    0    0    0    0    0    0    0    0
2:('스타', '링크')     0    0    0    0    0    0    0   11    0    0
1:('스타',)          0    0    0    0    0    0    0   11    0    0
1:('링크',)          0    0    0    0    0    0    0   11    0    0
1:('비용',)          0    0    0    0    0    0    0   11    0    0
1:('일부',)          5    2    0    0    0    2    0    1    0    0
1:('서비스',)         0    0    0    0    0    1    0    9    0    0
1:('변화',)         10    0    0    0    0    0    0    0    0    0
1:('헌혈',)          0    0    0    0    0    0    0    0    0   10
1:('사람',)          6    1    0    1    0    0    1    0    0    0
1:('LCC',)         0    0    0    0    0    0    0    9    0    0
1:('교황',)          0    0    0    0    0    0    8    0    0    0
1:('사업',)          0    0    0    0    8    0    0    0    0    0
1:('참가자',)         2    1    0    0    0    0    0    0    5    0
1:('뒤',)           3    0    0    1    0    1    0    1    2    0

* 고려해야 할 것은 분석 목적과 분야 입니다.

* n이 너무 크면 n-gram이 unique할 확률이 높아 등장수가 낮을 확률이 높아집니다.

In [42]:
def make_cooccurrence(words, window_size=2):
    vocab = sorted(set(words))
    word2id = {word: i for i, word in enumerate(vocab)}

    matrix = np.zeros(
        (len(vocab), len(vocab)),
        dtype=int
    )

    for i, center_word in enumerate(words):
        start = max(0, i - window_size)
        end = min(len(words), i + window_size + 1)

        for j in range(start, end):
            if i == j:
                continue

            context_word = words[j]

            matrix[
                word2id[center_word],
                word2id[context_word]
            ] += 1

    return pd.DataFrame(
        matrix,
        index=pd.Index(vocab, name="중심 단어"),
        columns=pd.Index(vocab, name="문맥 단어")
    )

selected_tokens = docs_tokens[7]

df_cooccurrence = make_cooccurrence(
    selected_tokens,
    window_size=2
)

print(news[7]["title"])

frequent_words = [
    word
    for word, count in Counter(selected_tokens).most_common(15)
]

display(
    df_cooccurrence.loc[frequent_words, frequent_words]
)

대형사 스타링크 무료 와이파이 경쟁, LCC는 속앓이

문맥 단어   스타  링크  비용  서비스  LCC  와이파이  대한항공  무료  기내  도입  항공기  기체  아시아나항공  제공  노선
중심 단어
스타       0  11   1    0    2     1     2   0   0   3    0   1       2   0   0
링크      11   0   0    0    2     1     0   2   0   3    0   1       2   0   0
비용       1   0   0    1    2     0     0   0   0   1    2   0       0   1   0
서비스      0   0   1    0    1     4     1   1   4   0    0   0       0   3   0
LCC      2   2   2    1    2     0     0   1   0   0    1   0       0   0   1
와이파이     1   1   0    4    0     0     0   4   4   0    1   0       0   2   0
대한항공     2   0   0    1    0     0     0   0   0   0    1   1       2   1   0
무료       0   2   0    1    1     4     0   0   3   0    1   0       0   0   0
기내       0   0   0    4    0     4     0   3   0   0    0   0       0   0   0
도입       3   3   1    0    0     0     0   0   0   0    0   0       0   0   0
항공기      0   0   2    0    1     1     1   1   0   0    0   0       0   0   0
기체       1   1   0    0    0     0     1   0   0   0    0   0       0   0   0
아시아나항공   2   2   0    0    0     0     2   0   0   0    0   0       0   0   0
제공       0   0   1    3    0     2     1   0   0   0    0   0       0   0   0
노선       0   0   0    0    1     0     0   0   0   0    0   0       0   0   0

* 고려해야 할 것은 문장 길이와 분석 목적입니다. window_size가 작으면 전체적인 맥락을 놓칠수도 있지만 변화에 민감해 집니다. 반대로 크면 노이즈에 강해지지만 이와 동시에 불필요한 노이즈가 섞일수도 있습니다.